// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCttzb7ZyRzpDg6nwfyF93BV7NInCXLnWU',
    appId: '1:484525981472:web:62d3cee19ed9e6734a6145',
    messagingSenderId: '484525981472',
    projectId: 'sos1-84fac',
    authDomain: 'sos1-84fac.firebaseapp.com',
    storageBucket: 'sos1-84fac.appspot.com',
    measurementId: 'G-SJ9N3CE3S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BOr0q4Pk-TWMaLhvFgegjS5KgjyslME',
    appId: '1:484525981472:android:7fa8da0f3183c4344a6145',
    messagingSenderId: '484525981472',
    projectId: 'sos1-84fac',
    storageBucket: 'sos1-84fac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEKJIfy87P7Lkd2YlHRcU9-AXlsIDe4ng',
    appId: '1:484525981472:ios:9adfd1569a2a756f4a6145',
    messagingSenderId: '484525981472',
    projectId: 'sos1-84fac',
    storageBucket: 'sos1-84fac.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEKJIfy87P7Lkd2YlHRcU9-AXlsIDe4ng',
    appId: '1:484525981472:ios:9adfd1569a2a756f4a6145',
    messagingSenderId: '484525981472',
    projectId: 'sos1-84fac',
    storageBucket: 'sos1-84fac.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCttzb7ZyRzpDg6nwfyF93BV7NInCXLnWU',
    appId: '1:484525981472:web:83691a641b9465f14a6145',
    messagingSenderId: '484525981472',
    projectId: 'sos1-84fac',
    authDomain: 'sos1-84fac.firebaseapp.com',
    storageBucket: 'sos1-84fac.appspot.com',
    measurementId: 'G-H1S3JHLP4E',
  );
}
